import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {ClerkProvider} from '@clerk/nextjs'
import React from "react";
import AtomProvider from "@/providers/AtomProvider";
import ToastProvider from "@/providers/ToastProvider";
import {ThemeProvider} from "@/providers/ThemeProvider";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by activity next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body className={inter.className}>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem>
                <ToastProvider/>
                <AtomProvider>
                    {children}
                </AtomProvider>
            </ThemeProvider>
            </body>
            </html>
        </ClerkProvider>
    )
}
